theme:
  background-color: 231 15 21
  primary-color: 265 89 79
  contrast-multiplier: 1.2
  positive-color: 135 94 66
  negative-color: 0 100 67

pages:
  - $include: home.yml

branding:
  custom-footer: '<span style="display:inline;white-space:nowrap;"><a href="https://feed-glance.onrender.com/">Dashboard</a>&nbsp;·&nbsp;<a href="https://linkedin.com/in/leonidchashnikov">LinkedIn</a>&nbsp;·&nbsp;<a href="https://github.com/RayanRal">GitHub</a></span>'
