- name: Home
  hide-desktop-navigation: true
  width: wide
  head-widgets:
    - type: group
      widgets:
        - type: rss
          title: Financial Times
          style: horizontal-cards
          thumbnail-height: 10
          limit: 8
          cache: 15m
          feeds:
            - url: https://www.ft.com/rss/home
              title: FT
        - type: markets
          title: Markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: META
              name: Meta
            - symbol: NVDA
              name: NVIDIA
            - symbol: GBPUSD=X
              name: GBP/USD
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: Europe/London
              label: London
            - timezone: Europe/Kyiv
              label: Kyiv
            - timezone: America/New_York
              label: New York
            - timezone: America/Los_Angeles
              label: SF

        - type: calendar
          first-day-of-week: monday

    - size: full
      widgets:
        - type: split-column
          max-columns: 2
          widgets:
            - type: group
              widgets:
                - type: hacker-news
                  limit: 14
                  cache: 1h
                  collapse-after: 7
                  sort-by: best
                  extra-sort-by: engagement
                  comments-url-template: https://news.ycombinator.com/item?id={POST-ID}

                - type: rss
                  title: Engineering Blogs
                  limit: 10
                  collapse-after: 7
                  cache: 2h
                  feeds:
                    - url: https://engineering.fb.com/feed/
                      title: Meta
                    - url: https://netflixtechblog.medium.com/feed
                      title: Netflix
                    - url: https://blog.cloudflare.com/rss/
                      title: Cloudflare
                    - url: https://slack.engineering/feed/
                      title: Slack
                    - url: https://aws.amazon.com/blogs/architecture/feed/
                      title: AWS
                    - url: https://github.blog/engineering/feed/
                      title: GitHub
                    - url: https://dropbox.tech/feed
                      title: Dropbox

            - type: group
              widgets:
                - type: lobsters
                  limit: 14
                  cache: 1h
                  collapse-after: 7
                  sort-by: hot
                  
                - type: reddit
                  subreddit: ExperiencedDevs
                  limit: 10
                  cache: 1h
                  collapse-after: 7
                  show-thumbnails: false
